name: haerospike
version: 0.1.0.0
github: "Diamondy4/haerospike"
license: MIT
author: "Diamondy4"
maintainer: "Diamondy4@hotmail.com"
copyright: "2022 Diamondy4"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/testy#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - inline-c
  - template-haskell

extra-libraries:
  - m
  - z
  - pthread
  - crypto
  - ssl
  - aerospike

library:
  source-dirs: src
  dependencies:
    - bytestring
    - containers
    - inline-c
    - template-haskell
  build-tools:
    - c2hs

executables:
  aerospike-example-exe:
    main: Main.hs
    source-dirs: example
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haerospike

tests:
  aerospike-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haerospike
